quarkus:
  datasource:
    db-kind: postgresql
    reactive:
      url: postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    jdbc: false

  hibernate-orm:
    log:
      sql: true
    schema-management:
      strategy: update

  hibernate-orm-active: false
  hibernate-reactive:
    active: true


infrastructure:
  adapter:
    out:
      api:
        asset:
          price-provider:
            token: ${PRICE_PROVIDER_API_TOKEN}

asset-price-provider:
  mp-rest:
    url: ${PRICE_PROVIDER_API_URL}