quarkus:
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    reactive:
      url: postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    schema-management:
      strategy: update

  rest-client:
    asset-price-provider:
      url: ${PRICE_PROVIDER_API_URL}

infrastructure:
  adapter:
    out:
      api:
        asset:
          price-provider:
            token: ${PRICE_PROVIDER_API_TOKEN}