quarkus:
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    reactive:
      url: postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:forgefolio}

  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    schema-management:
      strategy: none

  rest-client:
    asset-price-provider:
      url: ${PRICE_PROVIDER_API_URL:https://api.example.com/price}

infrastructure:
  adapter:
    out:
      api:
        asset:
          price-provider:
            token: ${PRICE_PROVIDER_API_TOKEN:your-api-token}