### create a new user
POST http://localhost:8080/users

### create a new portfolio
POST http://localhost:8080/portfolios
Content-Type: application/json

{
  "userId": "82fd8238-2b9d-4734-b566-655bda454434",
  "name": "My Portfolio"
}

### runs fetch asset prices scheduler
POST http://localhost:8080/scheduler/asset-prices/fetch

### get all assets
GET http://localhost:8080/assets
    ?page=0
    &size=3
    &sort=ticker:ASC
    &ticker=BBA

### create a new entry
POST http://localhost:8080/entries
Content-Type: application/json

{
  "portfolioId": "e5fa6457-b341-4a2a-b996-d1d775be02df",
  "assetId": "a9779df4-5bcf-4900-964b-1914173a56be",
  "date": "2025-07-14T12:34:03.283023Z",
  "type": "BUY",
  "amount": 10,
  "unitPrice": 21.19
}

### create a new goal
POST http://localhost:8080/goals
Content-Type: application/json

{
  "portfolioId": "e5fa6457-b341-4a2a-b996-d1d775be02df",
  "assetId": "a9779df4-5bcf-4900-964b-1914173a56be",

  "type": "PERCENTAGE",
  "percentage": 10
}