### create a new user
POST http://localhost:8080/users

### create a new portfolio
POST http://localhost:8080/portfolios
Content-Type: application/json

{
  "userId": "a468f3e8-98e9-4e05-b708-64160e3cd728",
  "name": "My Portfolio"
}

### runs fetch asset prices scheduler
POST http://localhost:8080/scheduler/asset-prices/fetch

### get all assets
GET http://localhost:8080/assets
    ?page=0
    &size=3
    &sort=ticker:ASC
    &ticker=BBA

### create a new entry
POST http://localhost:8080/entries
Content-Type: application/json

{
  "portfolioId": "a7974f90-ddd2-4d5a-8ec1-97db243c8bb4",
  "assetId": "ded37a4f-fc4d-4f3c-b53f-df57d483f7c9",
  "date": "2025-07-14T12:34:03.283023Z",
  "type": "BUY",
  "amount": 10,
  "unitPrice": 21.19
}